src/Nop.Plugin.Misc.HybridCache/Models/ConfigurationModel.cs
using System.Collections.Generic;
using System.ComponentModel;

namespace BAS.Nop.Plugin.Misc.HybridCache.Models
{
    public class ConfigurationModel
    {
        [DisplayName("Display Cache Stats")]
        public bool ShowCacheStats { get; set; }
        public Dictionary<string, string> CacheStats { get; set; }
        [DisplayName("Key To Search")]
        public string KeyToSearch { get; set; }
    }
}

src/Nop.Plugin.Misc.HybridCache/Controllers/HybridCacheConfigurationController.cs
using System.Collections.Generic;
using BAS.Nop.Plugin.Misc.HybridCache.Common;
using BAS.Nop.Plugin.Misc.HybridCache.Models;
using BAS.Nop.Plugin.Misc.HybridCache.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Nop.Services.Configuration;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Framework;
using Nop.Web.Framework.Mvc.Filters;

namespace BAS.Nop.Plugin.Misc.HybridCache.Controllers
{
    public class HybridCacheConfigurationController : BaseAdminController
    {
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly INotificationService _notificationService;
        private readonly IBusAccessor _busAccessor;
        private readonly IDistributedCacheStatMonitor _distributedCacheStatMonitor;

        public HybridCacheConfigurationController(IPermissionService permissionService,
            ISettingService settingService,
            INotificationService notificationService, IBusAccessor busAccessor, IDistributedCacheStatMonitor distributedCacheStatMonitor) 
        {
            _permissionService = permissionService;
            _settingService = settingService;
            _notificationService = notificationService;
            _busAccessor = busAccessor;
            _distributedCacheStatMonitor = distributedCacheStatMonitor;
        }

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSystemLog))
                return AccessDeniedView();

            var model = new ConfigurationModel
            {
            };

            return View(RouteConstants.ConfigurePluginPath, model);
        }

        /// <summary>
        /// Saves settings for plugin captured from view
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [AdminAntiForgery]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSystemLog))
                return AccessDeniedView();

            if (model.ShowCacheStats)
            {
                var message = new ServerSyncCommandData { Command = BusCommands.SHOW_CACHE_STATS, Data = new[] { model.KeyToSearch } };
                var messagejson = JsonConvert.SerializeObject(message);
                _busAccessor.Publish(BusConstants.SYNC_TOPIC, messagejson);
                model.CacheStats = _distributedCacheStatMonitor.GetAllCacheStats(model.KeyToSearch);
                model.CacheStats.Add("Local Results:", "Request made. Check logs.");
            }

            return View(RouteConstants.ConfigurePluginPath, model);
        }
    }
}

src/Nop.Plugin.Misc.HybridCache/Views/Admin/Configure.cshtml
@using BAS.Nop.Plugin.Misc.HybridCache.Models
@model BAS.Nop.Plugin.Misc.HybridCache.Models.ConfigurationModel
@{
    Layout = "_ConfigurePlugin";
}

<form asp-controller="HybridCacheConfiguration" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel">
            <div class="panel-body">
                <h1>Hybrid Cache Configuration</h1>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-2">
                        <nop-label asp-for="ShowCacheStats" />
                    </div>
                    <div class="col-md-10">
                        <nop-editor asp-for="ShowCacheStats" />
                        <span asp-validation-for="ShowCacheStats"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        <nop-label asp-for="KeyToSearch" />
                    </div>
                    <div class="col-md-10">
                        <nop-editor asp-for="KeyToSearch" />
                        <span asp-validation-for="KeyToSearch"></span>
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-9">
                        <input type="submit" name="save" class="btn bg-blue" value="Display" />
                    </div>
                </div>
                <hr />
                @if (Model.ShowCacheStats)
                {
                    <h3>Cache Stats</h3>
                    <div class="form-group">
                        <div class="col-md-12">
                            <table class="table table-bordered table-hover table-striped dataTable no-footer" width="100%" role="grid">
                                <thead>
                                    <tr role="row">
                                        <th>Key</th>
                                        <th>Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var reg in Model.CacheStats)
                                    { var showLogsLink = reg.Key == "Local Results:";
                                        <tr role="row">
                                            <td>@reg.Key</td>
                                            <td>@reg.Value 
                                            @if (showLogsLink) 
                                            {
                                                <a href="/Admin/Log/List">(Here)</a>
                                            }
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</form>